version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres16-db-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5436:5432'
    volumes:
      - authserver_pg_data:/var/lib/postgresql/data

volumes:
  authserver_pg_data:
